/**
 * The attribution SDK template inserted by the codemod into the target app.
 * This is a code template, NOT a raw string concatenated into files —
 * the ts-morph engine uses this as source text for a SourceFile it then
 * inserts into the target project's AST.
 *
 * SERVER_URL is replaced with the actual value during injection.
 */
export function getAttributionSdkSource(serverUrl: string, variants: Record<string, string>): string {
  const variantMapJson = JSON.stringify(variants, null, 2);
  return `import * as Linking from 'expo-linking';
import { useEffect, useState } from 'react';

const SERVER_URL = '${serverUrl}';

// Variant routing table generated by DropRoute during injection.
// Mapping: source param value -> variant key
const SOURCE_VARIANT_MAP: Record<string, 'a' | 'b'> = ${variantMapJson};

interface ReferralContext {
  ref: string | null;
  source: string | null;
  campaign: string | null;
}

let cachedContext: ReferralContext | null = null;

/**
 * Reads the initial deep link URL and extracts referral query params.
 * Call once on app mount via useEffect.
 */
export async function captureReferral(): Promise<ReferralContext> {
  if (cachedContext) return cachedContext;

  const initialUrl = await Linking.getInitialURL();
  if (!initialUrl) {
    cachedContext = { ref: null, source: null, campaign: null };
    return cachedContext;
  }

  const parsed = Linking.parse(initialUrl);
  const params = parsed.queryParams ?? {};

  cachedContext = {
    ref: (params['ref'] as string) ?? null,
    source: (params['source'] as string) ?? null,
    campaign: (params['campaign'] as string) ?? null,
  };

  return cachedContext;
}

/**
 * Reports a named event to the DropRoute attribution server,
 * attaching the captured referral context automatically.
 */
export async function reportEvent(
  eventName: string,
  metadata?: Record<string, unknown>
): Promise<void> {
  const ctx = cachedContext ?? (await captureReferral());

  try {
    await fetch(\`\${SERVER_URL}/api/events\`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        code: ctx.ref,
        eventName,
        metadata: {
          ...metadata,
          source: ctx.source,
          campaign: ctx.campaign,
        },
      }),
    });
  } catch {
    // Silently fail — attribution must never crash the app
  }
}

/**
 * Returns the active variant, headline, and cta deterministically derived from the referral source.
 * It actively listens to deep-linking foreground URL events to update the variant dynamically.
 */
export function useDropRouteVariant() {
  const [variant, setVariant] = useState<'default' | 'a' | 'b'>('default');
  const url = Linking.useURL();

  useEffect(() => {
    const parseUrl = async () => {
      let currentUrl = url;
      if (!currentUrl) {
        currentUrl = await Linking.getInitialURL();
      }
      
      if (currentUrl) {
        const parsed = Linking.parse(currentUrl);
        const source = parsed.queryParams?.source as string;
        
        if (source && SOURCE_VARIANT_MAP[source]) {
          setVariant(SOURCE_VARIANT_MAP[source]);
        } else {
          setVariant('default');
        }
      } else {
        setVariant('default');
      }
    };
    
    parseUrl();
  }, [url]);

  const headline =
    variant === 'a'
      ? 'Get started — exclusive offer inside'
      : variant === 'b'
      ? 'Welcome! Your friend sent you something special'
      : 'Welcome to the app';
      
  const cta =
    variant === 'a'
      ? 'Claim Your Offer'
      : variant === 'b'
      ? 'See What Awaits'
      : 'Get Started';

  return { variant, headline, cta };
}
`;
}
